version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod 
    command: gunicorn hello_world.wsgi:application --bind 0.0.0.0:8000
    volumes:
      # use volumes or mount
      # - static_volume:/app/staticfiles
      # - media_volume:/app/mediafiles
      - ./app/staticfiles:/app/staticfiles
      - ./app/mediafiles:/app/mediafiles
    expose:
      - 8000
    env_file:
      - ./app/.env.prod
    depends_on:
      - db
    restart: always
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    restart: always
  nginx:
    build: ./nginx
    volumes:
      # use volumes or mount
      # - static_volume:/app/staticfiles
      # - media_volume:/app/mediafiles
      - ./app/staticfiles:/app/staticfiles
      - ./app/mediafiles:/app/mediafiles
    ports:
      - 1234:80
    depends_on:
      - web
    restart: always
volumes:
  postgres_data:
  # use volumes or mount
  # static_volume:
  # media_volume: